### ISSUE TITLE
NoSuchMethodError with Gradle 8.0-rc-1

### ISSUE THREAD

**Issue by cloudshiftchris** [ljacomet/logging-capabilities#27]
When using with Gradle 8.0-rc-1 the below stack trace is generated:

```
* Exception is:
java.lang.NoSuchMethodError: 'void org.gradle.api.artifacts.DependencySubstitutions$Substitution.with(org.gradle.api.artifacts.component.ComponentSelector)'
	at dev.jacomet.gradle.plugins.logging.extension.LoggingCapabilitiesExtension.lambda$getSlf4JEnforcementSubstitutions$1(LoggingCapabilitiesExtension.java:436)
	at org.gradle.api.internal.artifacts.ivyservice.resolutionstrategy.DefaultResolutionStrategy.dependencySubstitution(DefaultResolutionStrategy.java:304)
	at dev.jacomet.gradle.plugins.logging.extension.LoggingCapabilitiesExtension.lambda$getSlf4JEnforcementSubstitutions$2(LoggingCapabilitiesExtension.java:434)
	at org.gradle.configuration.internal.DefaultUserCodeApplicationContext$CurrentApplication$1.execute(DefaultUserCodeApplicationContext.java:123)
	at org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAction$1.run(DefaultCollectionCallbackActionDecorator.java:110)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:47)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:68)
	at org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAction.execute(DefaultCollectionCallbackActionDecorator.java:107)
	at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:161)
	at dev.jacomet.gradle.plugins.logging.extension.LoggingCapabilitiesExtension.enforceSlf4JImplementation(LoggingCapabilitiesExtension.java:420)
	at dev.jacomet.gradle.plugins.logging.extension.LoggingCapabilitiesExtension.enforceLogback(LoggingCapabilitiesExtension.java:330)
	at cloudshift.gradle.plugin.java.JavaCorePlugin$configureDependencyResolution$2.invoke(JavaCorePlugin.kt:84)

```

**Comment by nakamorichi** [comment]
Should be fixed by #28

**Comment by ljacomet** [comment]
Thanks for the report and proposed fix.

This is indeed an API change in Gradle. I will try to see if I can do this in a way that does not force raising the minimal Gradle version this plugin supports.

**Comment by nakamorichi** [comment]
@ljacomet Is there need to support < 6.9.3? My team has Gradle version as old as 4.x in some modules, but mostly we have been able to migrate without much pain to 6.9.x (7.x caused issues for some plugins..). Unless there's strong reason to keep supporting legacy versions, might be most painless to just raise minimum support to 6.9.3.
